exclude = [
    ".idea",
    ".venv",
    ".github",
    ".devcontainer",
    ".vscode",
]

line-length = 120
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"

skip-magic-trailing-comma = false

docstring-code-format = false

docstring-code-line-length = "dynamic"
